[package]
name = "minitar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bincode = "1.3.3"
nix = "0.26.2"
serde = { version = "1.0.156", features = ["derive"] }
